# permissions for end users to view foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foo-viewer-role
rules:
- apiGroups:
  - tutorial.my.domain
  resources:
  - foos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorial.my.domain
  resources:
  - foos/status
  verbs:
  - get
